# Generated by Django 3.1.4 on 2021-01-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(upload_to='user/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(upload_to='user/images/'),
        ),
    ]
