# Generated by Django 3.1.4 on 2021-01-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210105_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(upload_to='user/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(upload_to='user/images/'),
        ),
    ]
