# Generated by Django 3.1.4 on 2021-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210131_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created',
            field=models.DateField(auto_now=True),
        ),
    ]
