# Generated by Django 3.1.4 on 2021-01-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210131_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Created',
            new_name='created',
        ),
    ]
